修復繁簡誤轉
NGLI/rime-wugniu_gninpou pull request #9
Opened 2022-10-16 08:11 UTC by groverlynn

修復詞庫中未被正確轉換為繁體的簡體字詞

2022-10-17 03:31 UTC, shinzoqchiuq requested changes
非常感謝！

我看了一下，大部分修改都沒有問題，有幾處還需再改的我標出來了。

2022-10-17 03:31 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
>  喂偏食	iu phi zhiq
也應修改。

2022-10-17 03:31 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
> +揹勿動	pei vaq don
`wugniu_gninpou.essay.dict.yaml` 收錄來自 `essay.txt` 的詞彙，對應的吳語詞收錄在 `wugniu_gninpou.phrase.dict.yaml`。
當修改 `wugniu_gninpou.phrase.dict.yaml` 相應行。
https://github.com/NGLI/rime-wugniu_gninpou/blob/e81c773db4d0af2b256f61b0413945bdf5512de1/wugniu_gninpou.phrase.dict.yaml#L4156-L4157

2022-10-17 03:31 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
> +籌劃	jieu waq
`essay.txt` 中「籌劃」「籌畫」均有收錄。此處不收「籌劃」是因爲「畫」是多音字而「劃」不是，不需要特別標註。

2022-10-17 03:31 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
> +背勿動	pei vaq don
見上，當修改 `wugniu_gninpou.phrase.dict.yaml` 相應行。

2022-10-17 03:31 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
> +鬥牛	teu ngeu
`essay.txt` 有收，且無需註音，當刪去。

2022-10-22 21:57 UTC, groverlynn commented on wugniu_gninpou.essay.dict.yaml
>  喂偏食	iu phi zhiq
該嗰詞是特例，勿用正字餵，用異體字喂（參考[國語辭典](https://dict.revised.moe.edu.tw/dictView.jsp?ID=161381&q=1&word=喂偏食)）

2022-10-22 22:20 UTC, groverlynn commented on wugniu_gninpou.essay.dict.yaml
> +傢俬	cia sy
格末下頭一軑 「傢俱」也重複
https://github.com/NGLI/rime-wugniu_gninpou/blob/e81c773db4d0af2b256f61b0413945bdf5512de1/wugniu_gninpou.essay.dict.yaml#L4123

https://github.com/NGLI/rime-wugniu_gninpou/blob/e81c773db4d0af2b256f61b0413945bdf5512de1/wugniu_gninpou.dict.yaml#L23417

2022-10-22 23:26 UTC, groverlynn commented on wugniu_gninpou.essay.dict.yaml
> +鬥牛	teu ngeu
該底弄錯嘞。應該是
```suggestion
鬥牛	teu ngeu
斗牛	teu gnieu
```
牽牛➡牛郎➡牛宿，從牽牛派生出來嗰應該統是gnieu

2022-10-23 02:53 UTC, shinzoqchiuq requested changes
「鬥牛」好刪掉。其他嘸沒問題了。

2022-10-23 02:53 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
>  喂偏食	iu phi zhiq
ok

2022-10-23 02:53 UTC, shinzoqchiuq commented on wugniu_gninpou.essay.dict.yaml
> +鬥牛	teu ngeu
𣍐錯。
但是 `wugniu_gninpou.dict.yaml` 裏向「牛」字 gnieu 個讀音字頻是1%。所以默認註音是 ngeu。「鬥牛」一詞 `essay.txt` 裏收過了，該底好甮再收。
https://github.com/NGLI/rime-wugniu_gninpou/blob/e81c773db4d0af2b256f61b0413945bdf5512de1/wugniu_gninpou.dict.yaml#L8291
「斗牛」也已經收錄過了，所以該底統刪掉就好了。
https://github.com/NGLI/rime-wugniu_gninpou/blob/e81c773db4d0af2b256f61b0413945bdf5512de1/wugniu_gninpou.essay.dict.yaml#L19220

2022-10-30 08:49 UTC, merged